#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
#실전투자 (모의투자인 경우 모의투자용 앱키, 앱시크리트 사용)

paper_app: "PSg96AIaXha3Q9XkEP1HEkBTFK3rgSW3B98t"
paper_sec: "gkZo3K6FK9uhDLJz5F20/TUA6OwofrYsJmHtK30e2ceEplJJrRwBhPuQiY7laLXan2IR5MVEnNaWU7TyJICYsdJ6SlR949xF9j7jY3fuu9FwxlkwxBYkWQ0MaX5N88kVUuZWeLD9/9axV2nEhUCi9kh5ZyghAxDLKEwc10b4ApFwugHtorM="

#계좌번호 앞 8자리
my_paper_stock: "50139658"
#계좌번호 뒤 2자리
my_prod: "01"

#실전투자
#prod: "https://openapi.koreainvestment.com:9443"
#모의투자
vps: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: ""

my_agent : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

